### PR TITLE
Support custom dns in vpn mode

### PR DESCRIPTION
**Pull request by hustlibraco**
Fixes # .

Changes proposed in this pull request:
- The default DNS server is 8.8.8.8 and does not support modification in VPN mode. But sometimes we need to specify a DNS server, such as in an intranet environment.

@mentions

### CODE REVIEW

**Comment by txthinking** [comment]
Thanks for your PR.
Can you test this change works on both macOS and Windows?

**Comment by hustlibraco** [comment]
I have used it for 10 days on Windows and it has performed well. I will test on MacOS when I have time.

**Comment by hustlibraco** [comment]
> I have used it for 10 days on Windows and it has performed well. I will test on MacOS when I have time.

I dont have a MacOS computer, and virtual macos is very troublesome >.< @txthinking

**Comment by txthinking** [comment]
Thank you, I will test it in few days.

**Pull request merged**
